name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validation:
    name: centralized validation
    uses: qtrpartners/jarvis-automation/.github/workflows/jarvis-ci.yml@4d785a25588c0959203391622f06e239759f1980
    permissions:
      contents: read
